### ISSUE TITLE
Deployed Phoenix app receiving `Internal server error`

### ISSUE THREAD

**Issue by aliciapflaumer** [aliciapflaumer/babble#7]
The deployed app on heroku is getting a `500 internal server error` when a user tries to either create a new account or sign-in. Works on localhost.

https://babble.herokuapp.com/

In the Network tab in the chrome console, it's saying the problem is in `sessions` on `POST`.

`heroku logs`:

```
2018-02-21T17:15:31.681623+00:00 app[web.1]: 
2018-02-21T17:15:31.681625+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.681626+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.681628+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.681630+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.681632+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:663: Postgrex.Protocol.bootstrap_send/6
2018-02-21T17:15:31.681633+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.handshake/2
2018-02-21T17:15:31.681635+00:00 app[web.1]:     (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
2018-02-21T17:15:31.681639+00:00 app[web.1]:     (connection) lib/connection.ex:741: Connection.connect/3
2018-02-21T17:15:31.681641+00:00 app[web.1]: Last message: {:timeout, #Reference<0.2534716226.3410755588.234838>, Connection}
2018-02-21T17:15:31.688271+00:00 app[web.1]: 17:15:31.687 [error] GenServer #PID<0.16886.1> terminating
2018-02-21T17:15:31.688275+00:00 app[web.1]: ** (RuntimeError) Connect raised a ArgumentError error. The exception details are hidden, as
2018-02-21T17:15:31.688277+00:00 app[web.1]: they may contain sensitive data such as database credentials.
2018-02-21T17:15:31.688278+00:00 app[web.1]: 
2018-02-21T17:15:31.688280+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.688282+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.688283+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.688285+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.688287+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:663: Postgrex.Protocol.bootstrap_send/6
2018-02-21T17:15:31.688288+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.handshake/2
2018-02-21T17:15:31.688290+00:00 app[web.1]:     (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
2018-02-21T17:15:31.688292+00:00 app[web.1]:     (connection) lib/connection.ex:622: Connection.enter_connect/5
2018-02-21T17:15:31.688294+00:00 app[web.1]: Last message: nil
2018-02-21T17:15:31.712524+00:00 app[web.1]: 17:15:31.695 [error] GenServer #PID<0.16887.1> terminating
2018-02-21T17:15:31.712532+00:00 app[web.1]: ** (RuntimeError) Connect raised a ArgumentError error. The exception details are hidden, as
2018-02-21T17:15:31.712534+00:00 app[web.1]: they may contain sensitive data such as database credentials.
2018-02-21T17:15:31.712536+00:00 app[web.1]: 
2018-02-21T17:15:31.712537+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.712539+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.712541+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.712543+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.712545+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:663: Postgrex.Protocol.bootstrap_send/6
2018-02-21T17:15:31.712546+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.handshake/2
2018-02-21T17:15:31.712548+00:00 app[web.1]:     (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
2018-02-21T17:15:31.712550+00:00 app[web.1]:     (connection) lib/connection.ex:622: Connection.enter_connect/5
2018-02-21T17:15:31.712552+00:00 app[web.1]: Last message: nil
2018-02-21T17:15:31.796636+00:00 app[web.1]: 17:15:31.792 [error] GenServer #PID<0.16891.1> terminating
2018-02-21T17:15:31.796639+00:00 app[web.1]: ** (RuntimeError) Connect raised a ArgumentError error. The exception details are hidden, as
2018-02-21T17:15:31.796641+00:00 app[web.1]: they may contain sensitive data such as database credentials.
2018-02-21T17:15:31.796643+00:00 app[web.1]: 
2018-02-21T17:15:31.796644+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.796646+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.796648+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.796649+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.796651+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:663: Postgrex.Protocol.bootstrap_send/6
2018-02-21T17:15:31.796653+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.handshake/2
2018-02-21T17:15:31.796655+00:00 app[web.1]:     (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
2018-02-21T17:15:31.796656+00:00 app[web.1]:     (connection) lib/connection.ex:622: Connection.enter_connect/5
2018-02-21T17:15:31.796658+00:00 app[web.1]: Last message: nil
2018-02-21T17:15:31.798975+00:00 app[web.1]: 17:15:31.798 [error] GenServer #PID<0.16892.1> terminating
2018-02-21T17:15:31.798977+00:00 app[web.1]: ** (RuntimeError) Connect raised a ArgumentError error. The exception details are hidden, as
2018-02-21T17:15:31.798979+00:00 app[web.1]: they may contain sensitive data such as database credentials.
2018-02-21T17:15:31.798980+00:00 app[web.1]: 
2018-02-21T17:15:31.798982+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.798984+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.798985+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.798987+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.798989+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:663: Postgrex.Protocol.bootstrap_send/6
2018-02-21T17:15:31.798990+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.handshake/2
2018-02-21T17:15:31.798992+00:00 app[web.1]:     (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
2018-02-21T17:15:31.798993+00:00 app[web.1]:     (connection) lib/connection.ex:622: Connection.enter_connect/5
2018-02-21T17:15:31.798995+00:00 app[web.1]: Last message: nil
2018-02-21T17:15:31.808053+00:00 app[web.1]: 17:15:31.807 [error] GenServer #PID<0.16894.1> terminating
2018-02-21T17:15:31.808056+00:00 app[web.1]: ** (RuntimeError) Connect raised a ArgumentError error. The exception details are hidden, as
2018-02-21T17:15:31.808058+00:00 app[web.1]: they may contain sensitive data such as database credentials.
2018-02-21T17:15:31.808060+00:00 app[web.1]: 
2018-02-21T17:15:31.808061+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.808063+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.808064+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.808066+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.808068+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:663: Postgrex.Protocol.bootstrap_send/6
2018-02-21T17:15:31.808069+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.handshake/2
2018-02-21T17:15:31.808071+00:00 app[web.1]:     (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
2018-02-21T17:15:31.808072+00:00 app[web.1]:     (connection) lib/connection.ex:622: Connection.enter_connect/5
2018-02-21T17:15:31.808074+00:00 app[web.1]: Last message: nil
2018-02-21T17:15:31.847893+00:00 app[web.1]: 17:15:31.847 [error] GenServer #PID<0.16902.1> terminating
2018-02-21T17:15:31.847897+00:00 app[web.1]: ** (RuntimeError) Connect raised a ArgumentError error. The exception details are hidden, as
2018-02-21T17:15:31.847902+00:00 app[web.1]: they may contain sensitive data such as database credentials.
2018-02-21T17:15:31.847904+00:00 app[web.1]: 
2018-02-21T17:15:31.847905+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.847907+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.847909+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.847910+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.847912+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:663: Postgrex.Protocol.bootstrap_send/6
2018-02-21T17:15:31.847914+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.handshake/2
2018-02-21T17:15:31.847915+00:00 app[web.1]:     (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
2018-02-21T17:15:31.847917+00:00 app[web.1]:     (connection) lib/connection.ex:622: Connection.enter_connect/5
2018-02-21T17:15:31.847919+00:00 app[web.1]: Last message: nil
2018-02-21T17:15:31.859943+00:00 app[web.1]: 17:15:31.858 [error] GenServer #PID<0.16901.1> terminating
2018-02-21T17:15:31.859946+00:00 app[web.1]: ** (RuntimeError) Connect raised a ArgumentError error. The exception details are hidden, as
2018-02-21T17:15:31.859948+00:00 app[web.1]: they may contain sensitive data such as database credentials.
2018-02-21T17:15:31.859950+00:00 app[web.1]: 
2018-02-21T17:15:31.859952+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.859953+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.859955+00:00 app[web.1]:     (elixir) lib/enum.ex:1255: Enum."-map/2-lists^map/1-0-"/2
2018-02-21T17:15:31.859957+00:00 app[web.1]:     (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
2018-02-21T17:15:31.859958+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:663: Postgrex.Protocol.bootstrap_send/6
2018-02-21T17:15:31.859960+00:00 app[web.1]:     (postgrex) lib/postgrex/protocol.ex:497: Postgrex.Protocol.handshake/2
2018-02-21T17:15:31.859961+00:00 app[web.1]:     (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
2018-02-21T17:15:31.859963+00:00 app[web.1]:     (connection) lib/connection.ex:622: Connection.enter_connect/5
2018-02-21T17:15:31.859965+00:00 app[web.1]: Last message: nil
```

**Comment by aliciapflaumer** [comment]
Found this thread on [stackoverflow](https://stackoverflow.com/questions/36193141/phoenix-ueberauth-google-heroku-internal-server-error):

Tried adding `:httpoison` to list of dependencies in `mix.exs` file.

Pushed to heroku and still getting `internal server error`

**Comment by aliciapflaumer** [comment]
I posted my issue on elixir form [here](https://elixirforum.com/t/phoenix-chat-app-crashes-with-internal-server-error-when-perforing-authorization/15318/7).

The solution: 
1) I updated postgrex with `mix deps.update postgrex`
and when that didn't solve it, I did:
2) I ran db migrations on heroku with `heroku run mix ecto.migrate`
That solved the `internal server error` on deployed app.
